version: "3"
services:
    db:
        image: "mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04"
        environment:
            SA_PASSWORD: "${MSSQLPASSWORD}"
            ACCEPT_EULA: "Y"
        ports: 
            - "1433:1433"
            
    parser:
        build: ./MtgParser
        environment:
            ASPNETCORE_ENVIRONMENT: "Docker"
        ports: 
            - "5084:80"
            
    image-service:
        build: ./ImageService
        environment:
            ASPNETCORE_ENVIRONMENT: "Docker"
        ports: 
            - "5085:80"
